name: poetic.machines
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - jupyter
  - matplotlib
  - numpy
  - opencv
  - pillow
  - pycairo
  - ollama
  - ollama-python
  - markdown
  - pip:
    - strip-markdown
    - py5canvas
    - mediapipe
